accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    #path('', views.HomePageView.as_view(), name='home'),
    path('', views.ListGroups.as_view(), name='groups_list'),
    path('new/', views.CreateGroupView.as_view(), name='create'),
    path('posts/in/<slug>', views.SingleGroup.as_view(), name='single'),
    # path('join/<slug>', views.JoinGroup.as_view(), name='join'),
    # path('leave/<slug>', views.LeaveGroup.as_view(), name='leave'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='groups_list'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='home'),
    path('test/', views.TestPageView.as_view(), name='test'),
    path('thanks/', views.ThanksPageView.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('posts/', include('posts.urls')),
    # path('groups/', include('groups.urls')),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
import misaka

from django.contrib.auth import get_user_model
# Groups models.py
# Create your models here.
User = get_user_model()
from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False,default='', blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka
from groups.models import Group
from django.contrib.auth import get_user_model
User = get_user_model()
###POSTS Models.py
# Create your models here.
class Post(models.Model):
     post_user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
     created_at = models.DateTimeField(auto_now=True)
     message = models.TextField()
     message_html = models.TextField(editable=False,default='', blank=True)
     group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

     def __str__(self):
         return self.message

     def save(self, *args, **kwargs):
         self.message_html = misaka.html(self.message)
         super().save(*args, **kwargs)

     def get_absolute_url(self):
         return reverse('posts:single', kwargs={'username':self.user.username,
                                                'pk':self.pk})

     class Meta:
         ordering = ['-created_at']
         unique_together = ['user','message']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse, reverse_lazy
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from groups.models import Group, GroupMember

# Create your views here.
class CreateGroupView(LoginRequiredMixin,generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

posts/views.py
from django.shortcuts import render
from posts.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from braces.views import SelectRelatedMixin
from . import forms
from django.contrib.auth import get_user_model
# Create your views here.
User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    model = Post
    select_related = ('user', 'group')

class UserPosts(generic.ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    model = Post
    fields = ('message', 'group')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.post_user = self.request.post_user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

simplesocial/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home.html'

class TestPageView(TemplateView):
    template_name = 'test.html'

class ThanksPageView(TemplateView):
    template_name = 'thanks.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <h1>Login!</h1>
  <form class="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-outline-dark" type="submit" name="Submit" value="Login">
  </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <h1>Sign Up!</h1>
  <form class="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-outline-dark" type="submit" name="Submit" value="Sign Up">
  </form>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
<h1>{{group.name}}</h1>
<h2>{{group.members.count}}</h2>
<div class="content">
  {% if user in group.members.all %}
  <a href="{% url 'groups:leave' slug=group.slug %}" class='btn btn-lg btn-warning'><span class="fa fa-times-circle-o"></span> Leave</a>
  {% else %}
  <a href="{% url 'groups:leave' slug=group.slug %}" class='btn btn-lg btn-warning'><span class="fa fa-check-circle-o"></span> Join</a>
  {% endif %}
</div>
{% endblock %}
{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count == 0 %}
  <h2>No posts in this group yet!</h2>
  {% else %}
  {% for post in group.posts.all %}
  {% include "posts/_post.html" }
  {% endfor %}
  {% endif %}
</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<div class="col-md-8">
  <div class="content">
    {% if user.is_authenticated %}
    <h2>
    Welcome Back
    <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
    </h2>
    {% endif %}
    <h2>Groups</h2>
    <p>Welcome to the Groups Page! <br>Select a Group with a shared interest!</p>
  </div>
  {% if user.is_authenticated %}
  <a href="{% url 'groups:create' %}" class="btn btn-warning" role='button'><span class="fa fa-plus"></span>Create New Group</a>
  {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  <div class="list_group">
    {% for group in object_list %}
    <a href="{% url 'groups:single' slug=group.slug %}"
    class="list-group-item list-group-item-action flex-column align-items-start">
    <h3 class='mb-1'>{{group.name}}</h3>
    <p class='mb-1'>{{group.description_html|safe}}</p>
    <div class="d-flex w-40 justify-content-between">
      <small class='text-muted'><span class='badge badge-secondary'>
        {{group.members.count}}</span>member{{group.members.count|pluralize}}</small>
        <small class='text-muted'><span class='badge badge-secondary'>
          {{group.posts.count}}</span>member{{group.posts.count|pluralize}}</small>
          <span></span><span></span>
    </div>
  </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

groups/templates/groups/groups_base.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>
{% endblock %}

groups/templates/groups/groups_form.html
{% extends 'groups/group_base.html' }
{% load bootstrap4 %}

{% block group_content %}
<div class="container">
  <h4> Create a new Group </h4>
  <form class="" action="{% url 'groups:create' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary btn-large" name="button">Create</button>
  </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="#" class="btn btn-simple">Post</a>
            <a class="nav-item nav-link" href="#" class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="#" class="btn btn-simple">Create Group</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
          {% else %}
            <a class="nav-item nav-link" href="#"class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

    <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome to Star Social!!!!</h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>You are logged in!</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visiting, come back soon!</h1>
{% endblock %}